### PR TITLE
This is a signinficant refactor. It should be backwards compatible, w…

### PR DESCRIPTION
**Pull request by dcal**
…hile also expsing a new Event interface and serialization strategies that allow a publisher or consumer to use mime types via SQS attributes.

### CODE REVIEW

**Comment by aemadrid** [comment]
After a quick pass here are some first impressions:

* in general the move looks good
* I'm concerned though that moving some classes around (e.g. `Event` to `Consumers::Event`) could break current projects using the library without adding much value
* it seems light on the testing side. I would love to see more testing proving that you can encode/decode both the old and new way without issues

I'm not sure when I could do a more thorough review but these things stood out on a very first quick read.

**Comment by dcal** [comment]
At a high level, the "encoding" concept has been extracted into the concept of "serialization strategies." Serialization strategies are an aggregate concept of serialization + formatting the message for SQS. Event objects know how to serialize and deserialize themselves using these strategies. The current "#publish" method will keep the same interface, but use defaults from configuration to build an Event object. The "#publish_event" interface (which is what #publish uses behind the scenes) will allow the developer to supply a custom Event object and specify serialization and deserialization strategies.


> After a quick pass here are some first impressions:
> 
> * in general the move looks good
> * I'm concerned though that moving some classes around (e.g. `Event` to `Consumers::Event`) could break current projects using the library without adding much value
> * it seems light on the testing side. I would love to see more testing proving that you can encode/decode both the old and new way without issues
> 
> I'm not sure when I could do a more thorough review but these things stood out on a very first quick read.

@aemadrid I'll see if I can add some integration tests in that regard. I'll reconsider some of the moved classes.

**Comment by aemadrid** [comment]
@dcal let me be more clear. I see the value in moving the event class and known how to serialize/deserialize itself. I'm not sure though if any of the projects using Tiki have customized that class or any of classes moved. We would need to check each project and make sure we don't break anything there. If we don't I'm all for the change.

**Comment by dcal** [comment]
@aemadrid Sounds good, I actually took your comment to mean that, so we are on the same page. I'm asking Ben to get his team to look at these changes and see if they would break anything. Thanks for the feedback.

**Pull request closed without merging**
